<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  >
    <xacro:include filename="inertial_macros.xacro" />

    <xacro:macro name="arm_generator" params="suffix parent ph sizex sizey sizez upper lower">
        <!-- arm macro -->
    <joint name="${suffix}_arm_joint" type="revolute" >
        <limit effort="5" velocity="2.1750" lower="${lower}" upper="${upper}"/>
        <parent link="${parent}_link" />
        <child link="${suffix}_arm_link" />
        <origin xyz="0 0 ${ph}" />
    </joint> 
    <link name="${suffix}_arm_link">
        <visual>
            <origin xyz="0 0 ${sizez/2}"/>
            <geometry>
                <box size="${sizex} ${sizey} ${sizez}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${sizez/2}"/>
            <geometry>
                <box size="${sizex} ${sizey} ${sizez}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.3" x="${sizex}" y="${sizey}" z="${sizez}" >
            <origin xyz="0 0 ${sizez/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>
    </xacro:macro>  
    <xacro:macro name="base_arm_generator" params="suffix parent ph radius length">
        <!-- arm macro -->
        <joint name="base_${suffix}_arm_joint" type="fixed" >
            <parent link="${parent}_link" />
            <child link="base_${suffix}_arm_link" />
            <origin xyz="0 0 ${ph}" />
        </joint> 

        <link name="base_${suffix}_arm_link" >
            <visual>
                <origin xyz="0 0 ${radius/2}" rpy="${pi/2} 0 ${pi/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${radius/2}" rpy="${pi/2} 0 ${pi/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                
            </collision>
            <xacro:inertial_cylinder mass="0.3" radius="${radius}" length="${length}" >
                <origin xyz="0 0 ${radius/2}" rpy="${pi/2} 0 ${pi/2}" />
            </xacro:inertial_cylinder>

        </link>
    </xacro:macro>  

</robot>